In [1]:
import numpy as np

In [3]:
a=[1]
a

[1]

In [9]:
a0=np.array([1])
a1=np.array([1,2,3,4,5])
a2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
a3=np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])

In [11]:
a0

array([1])

In [13]:
print(a2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [15]:
a1

array([1, 2, 3, 4, 5])

In [17]:
print(a2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [19]:
a3

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [21]:
a0.shape

(1,)

In [23]:
a1.shape

(5,)

In [25]:
a2.shape

(2, 5)

In [27]:
a3.shape

(2, 2, 5)